"""Resampling-based parameter uncertainty estimation."""

import warnings
import numpy as np

__all__ = [
    'Bootstrap',
    'bootstrap',
    'attach',
    'detach',
    'ResampleError',
]


class ResampleError(Exception):
    """Raised when resampling fails or inputs are invalid."""


def is_batched_result_like(model) -> bool:
    """Return True for MultiFit-like containers (batched spectra/cubes)."""
    return (
        hasattr(model, 'n_spaxels')
        and hasattr(model, 'get_model')
        and hasattr(model, 'param_names')
    )


def prepare_noise_and_weights(y, yerr, weights, statistic):
    """
    Normalize yerr/weights inputs and return both arrays.
    - If only weights are provided, derive yerr for noise generation.
    - If only yerr is provided, compute chi-squared style weights.
    - If neither is provided and statistic is Poisson, synthesize yerr/weights.
    """
    stat = statistic.lower()

    if yerr is None:
        if weights is not None:
            weights = np.asarray(weights)
            if np.any(~np.isfinite(weights)):
                raise ResampleError("weights contains non-finite values.")
            safe_weights = np.maximum(weights, 1e-20)
            yerr = np.sqrt(1.0 / safe_weights)
        elif stat == 'poisson':
            base = np.maximum(np.abs(y), 1)
            yerr = np.sqrt(base)
        else:
            raise ResampleError(
                "yerr or weights required for Gaussian bootstrap. "
                "Provide data uncertainties or weights for noise generation."
            )

    yerr = np.asarray(yerr, dtype=float)
    if yerr.ndim not in {1, 2}:
        raise ResampleError('yerr must be symmetric (N,) or asymmetric (2, N).')
    if yerr.ndim == 2 and yerr.shape[0] != 2:
        raise ResampleError('Asymmetric yerr must have shape (2, N).')
    yerr = np.maximum(yerr, 1e-10)
    if np.any(~np.isfinite(yerr)):
        raise ResampleError("yerr contains non-finite values.")

    effective_yerr = 0.5 * (yerr[0] + yerr[1]) if yerr.ndim == 2 else yerr

    if weights is None:
        if stat == 'poisson':
            weights = 1.0 / np.maximum(np.abs(y), 1e-10)
        else:
            weights = 1.0 / (effective_yerr ** 2)
    else:
        weights = np.asarray(weights)
        if np.any(~np.isfinite(weights)):
            raise ResampleError("weights contains non-finite values.")
        weights = np.maximum(weights, 1e-20)

    return yerr, effective_yerr, weights


def extract_limits(param, param_samples, lower_percentile, upper_percentile,
                   boundary_epsilon=1e-10, boundary_tolerance=0.5):
    """Extract confidence limits with simple boundary truncation detection."""
    valid_samples = param_samples[~np.isnan(param_samples)]
    if len(valid_samples) == 0:
        return np.nan, np.nan

    lolim = np.percentile(valid_samples, lower_percentile)
    uplim = np.percentile(valid_samples, upper_percentile)

    has_lower_bound = hasattr(param, 'min') and param.min is not None
    has_upper_bound = hasattr(param, 'max') and param.max is not None

    at_lower = 0
    at_upper = 0
    if has_lower_bound:
        at_lower = np.sum(valid_samples <= param.min + boundary_epsilon)
    if has_upper_bound:
        at_upper = np.sum(valid_samples >= param.max - boundary_epsilon)

    if at_lower == 0 and at_upper == 0:
        return lolim, uplim

    iqr = np.percentile(valid_samples, 75) - np.percentile(valid_samples, 25)
    tolerance = max(boundary_tolerance * iqr, 1e-10)

    if has_lower_bound and at_lower > 0:
        if (lolim - param.min) < tolerance:
            lolim = np.nan

    if has_upper_bound and at_upper > 0:
        if (param.max - uplim) < tolerance:
            uplim = np.nan

    return lolim, uplim


class Bootstrap:
    """Flux Randomization (Empirical Monte Carlo) uncertainty estimator.

    Synthetic datasets are generated by perturbing the observed data with
    the measured uncertainties, not from the fitted model. This preserves
    systematic residuals and is appropriate when the model is phenomenological
    or incomplete (e.g., multi-Gaussian emission-line fitting).

    For each iteration, pixel i is drawn as:

    - ``gauss``:   y_new[i] ~ Normal(y_obs[i], sigma[i])
    - ``uniform``: y_new[i] ~ Uniform(y_obs[i] ± √3·sigma[i])
                   (bounds scaled by √3 so that Var = sigma²,
                    matching the Gaussian case)
    - ``poisson``: y_new[i] ~ Poisson(lam = y_obs[i])
                   (requires raw non-negative integer counts)

    The original uncertainty array is passed unchanged to the fitter in every
    iteration — only the flux values are perturbed.

    References
    ----------
    Peterson et al. (1998), PASP 110, 660 — flux randomization for
    emission-line uncertainty estimation.
    """

    def __init__(self, model, fitter=None, x=None, y=None, yerr=None, weights=None,
                 n_samples=1000, statistic='gauss', fitter_kwargs=None,
                 seed=None, confidence=68, noise_dist='uniform',
                 verbose=True, nproc=1, batch=False,
                 inplace=True, set_values=True, xerr=None, perturb_x=False):
        # Frozen copy: all bootstrap iterations start from this state.
        # The original model is never mutated during the run.
        self._initial_model = model.copy()
        self.model = model
        if fitter is None:
            from ..scipyfit import ScipyTRF
            fitter = ScipyTRF()
        self.fitter = fitter
        self.x = np.asarray(x)
        self.y = np.asarray(y)
        self.xerr = None if xerr is None else np.asarray(xerr, dtype=float)
        self.yerr = yerr
        self.weights = weights
        self.n_samples = int(n_samples)
        self.statistic = statistic
        self.fitter_kwargs = {} if fitter_kwargs is None else dict(fitter_kwargs)
        self.seed = seed
        self.verbose = bool(verbose)
        self.nproc = int(nproc)
        self.batch = bool(batch)
        self.inplace = bool(inplace)
        self.confidence = confidence
        self.set_values = bool(set_values)
        self.noise_dist = noise_dist.lower()
        self.perturb_x = bool(perturb_x)

    @staticmethod
    def _fit_param_names(model):
        from astropy.modeling.fitting import model_to_fit_params

        _, fit_indices, _ = model_to_fit_params(model)
        names = []
        cumulative_idx = 0
        for pname in model.param_names:
            param = getattr(model, pname)
            for offset in range(param.size):
                if cumulative_idx in fit_indices:
                    names.append(pname if param.size == 1 else f"{pname}[{offset}]")
                cumulative_idx += 1
        return names

    def run(self):
        """Run bootstrap and return parameter sample arrays."""
        from astropy.modeling.fitting import model_to_fit_params

        if is_batched_result_like(self.model):
            raise NotImplementedError(
                "Resampling for batched spectra/cubes is not implemented yet. "
                "Use ad-hoc single-spectrum fitting for bootstrap uncertainties."
            )

        stat = self.statistic.lower()
        if stat not in {'gauss', 'poisson'}:
            raise ResampleError(f"Unknown statistic '{self.statistic}'. Use 'gauss' or 'poisson'.")

        if self.noise_dist not in {'gauss', 'uniform'}:
            raise ResampleError(f"Unknown noise distribution '{self.noise_dist}'. Use 'gauss' or 'uniform'.")

        if self.n_samples < 1:
            raise ResampleError("n_samples must be >= 1.")

        raw_yerr, fit_yerr, weights = prepare_noise_and_weights(self.y, self.yerr, self.weights, stat)
        # Flux Randomization: perturb observed data with measured uncertainties.
        # The observed spectrum carries the signal; only the noise realization
        # changes across iterations (Peterson et al. 1998, PASP 110, 660).
        y_obs = np.asarray(self.y, dtype=float)
        n_pts = y_obs.size
        _sqrt3 = np.sqrt(3.0)

        if raw_yerr.ndim == 2 and self.noise_dist == 'gauss':
            raise ResampleError(
                "Asymmetric yerr is ambiguous for Gaussian resampling. "
                "Use noise_dist='uniform' or provide symmetric yerr."
            )

        if self.perturb_x:
            if self.xerr is None:
                raise ResampleError('perturb_x=True requires explicit xerr.')
            if self.xerr.ndim != 1:
                raise ResampleError('Only symmetric xerr is supported when perturb_x=True.')
            if self.xerr.shape != self.x.shape:
                raise ResampleError('xerr must match x shape when perturb_x=True.')
            if np.any(~np.isfinite(self.xerr)) or np.any(self.xerr < 0):
                raise ResampleError('xerr must be finite and non-negative.')

        rng = np.random.default_rng(self.seed)
        if stat == 'gauss':
            if self.noise_dist == 'uniform':
                # ±√3·σ gives Var = σ², matching the Gaussian case.
                if raw_yerr.ndim == 2:
                    y_synth = rng.uniform(
                        y_obs - raw_yerr[0],
                        y_obs + raw_yerr[1],
                        size=(self.n_samples, n_pts),
                    )
                else:
                    y_synth = rng.uniform(
                        y_obs - _sqrt3 * raw_yerr,
                        y_obs + _sqrt3 * raw_yerr,
                        size=(self.n_samples, n_pts),
                    )
            else:
                y_synth = rng.normal(y_obs, raw_yerr, size=(self.n_samples, n_pts))
            fit_stat = 'chi2'
        else:
            # Poisson: λ = observed counts. y_obs must be raw non-negative counts.
            lam = np.maximum(y_obs, 0.0)
            y_synth = rng.poisson(lam, size=(self.n_samples, n_pts)).astype(float)
            fit_stat = 'poisson'

        if self.perturb_x:
            if self.noise_dist == 'uniform':
                x_synth = rng.uniform(
                    self.x - _sqrt3 * self.xerr,
                    self.x + _sqrt3 * self.xerr,
                    size=(self.n_samples, n_pts),
                )
            else:
                x_synth = rng.normal(self.x, self.xerr, size=(self.n_samples, n_pts))
        else:
            x_synth = None

        yerr_batch = np.broadcast_to(fit_yerr, (self.n_samples, n_pts))
        weights_batch = np.broadcast_to(weights, (self.n_samples, n_pts))

        param_names = self._fit_param_names(self._initial_model)
        samples = {name: np.full(self.n_samples, np.nan, dtype=float) for name in param_names}

        n_success = 0
        max_warn = 5
        warned = 0
        if x_synth is None:
            result = self.fitter.multifit(
                model=self._initial_model.copy(),
                x=self.x,
                y=y_synth,
                yerr=yerr_batch,
                weights=weights_batch,
                statistic=fit_stat,
                nproc=self.nproc,
                progress=True,
                batch=self.batch,
                **self.fitter_kwargs,
            )

            for i in range(self.n_samples):
                if not bool(result.success.flat[i]):
                    if self.verbose and warned < max_warn:
                        warnings.warn(
                            f"Bootstrap iteration {i} failed: {result.messages.flat[i]}",
                            RuntimeWarning,
                        )
                        warned += 1
                    continue

                fitted_model = result.get_model(i)
                fitted_params, _, _ = model_to_fit_params(fitted_model)
                for name, value in zip(param_names, fitted_params):
                    samples[name][i] = value
                n_success += 1

            nfev_arr = result.nfev.ravel()
        else:
            nfev_arr = np.full(self.n_samples, np.nan, dtype=float)
            for i in range(self.n_samples):
                try:
                    fitted_model = self.fitter(
                        model=self._initial_model.copy(),
                        x=x_synth[i],
                        y=y_synth[i],
                        yerr=fit_yerr,
                        weights=weights,
                        statistic=fit_stat,
                        inplace=False,
                        **self.fitter_kwargs,
                    )
                except Exception as exc:
                    if self.verbose and warned < max_warn:
                        warnings.warn(f'Bootstrap iteration {i} failed: {exc}', RuntimeWarning)
                        warned += 1
                    continue

                fitted_params, _, _ = model_to_fit_params(fitted_model)
                for name, value in zip(param_names, fitted_params):
                    samples[name][i] = value
                n_success += 1

        # Post-run diagnostic: warn if most fits barely moved
        valid_nfev = nfev_arr[np.isfinite(nfev_arr)]
        if len(valid_nfev) > 0:
            frac_stale = np.mean(valid_nfev < 3)
            if frac_stale > 0.5:
                warnings.warn(
                    f"{frac_stale * 100:.0f}% of bootstrap fits converged in <3 "
                    f"function evaluations (nfev<3), suggesting the fitter is not "
                    f"re-optimizing the perturbed data. This leads to underestimated "
                    f"uncertainties. Consider using ScipyTRF() or SherpaLM() as the "
                    f"bootstrap fitter.",
                    RuntimeWarning,
                )

        # Post-run diagnostic: warn if all samples are identical (degenerate)
        if n_success > 1:
            vals = np.column_stack(
                [samples[name] for name in param_names])
            valid_mask = np.all(np.isfinite(vals), axis=1)
            valid_vals = vals[valid_mask]
            if valid_vals.shape[0] > 1:
                spread = np.ptp(valid_vals, axis=0)
                if np.all(spread == 0.0):
                    warnings.warn(
                        "All bootstrap parameter samples are identical. "
                        "The fitter converged to the same solution for every "
                        "noise realization. Uncertainties are unreliable. "
                        "Possible causes: the fitter is stuck at a hard "
                        "minimum, tolerance is too loose, or parameter "
                        "bounds are too tight.",
                        RuntimeWarning,
                    )

        success_rate = n_success / self.n_samples
        if success_rate < 0.9:
            warnings.warn(
                f"Only {success_rate * 100:.1f}% of bootstrap iterations succeeded. "
                "Results may be unreliable.",
                RuntimeWarning,
            )

        if self.verbose:
            print(f"✓ Bootstrap complete: {n_success}/{self.n_samples} successful")

        if self.inplace:
            Bootstrap.attach(
                self.model, samples,
                confidence=self.confidence,
                set_values=self.set_values,
                verbose=self.verbose,
            )

        return samples

    @staticmethod
    def attach(model, samples, confidence=68, percentiles=None, verbose=False, set_values=True):
        """Attach bootstrap uncertainties to model parameters in-place."""
        if is_batched_result_like(model):
            raise NotImplementedError(
                "Attaching resampling limits to batched spectra/cubes is not implemented yet. "
                "Use ad-hoc single-spectrum fitting for uncertainty attachment."
            )

        if percentiles is None:
            percentiles = [16, 50, 84]
        if 50 not in percentiles:
            percentiles = list(percentiles) + [50]

        alpha = (100 - confidence) / 2
        lower_percentile = alpha
        upper_percentile = 100 - alpha

        for param_name, param_samples in samples.items():
            if '[' in param_name:
                base_name = param_name.split('[')[0]
                idx = int(param_name.split('[')[1].rstrip(']'))
                param = getattr(model, base_name)

                if not hasattr(param, 'std') or param.std is None or np.isscalar(param.std):
                    param.std = np.full(param.size, np.nan)
                    param.median = np.full(param.size, np.nan)
                    param.lolim = np.full(param.size, np.nan)
                    param.uplim = np.full(param.size, np.nan)
                    param.percentiles = {}

                valid_samples = param_samples[~np.isnan(param_samples)]
                if len(valid_samples) == 0:
                    continue

                param.std[idx] = np.std(valid_samples)
                param.median[idx] = np.percentile(valid_samples, 50)
                lolim, uplim = extract_limits(param, param_samples, lower_percentile, upper_percentile)
                param.lolim[idx] = lolim
                param.uplim[idx] = uplim

                for p in percentiles:
                    if p not in param.percentiles:
                        param.percentiles[p] = np.full(param.size, np.nan)
                    param.percentiles[p][idx] = np.percentile(valid_samples, p)

                if set_values and np.isfinite(param.median[idx]):
                    updated = np.array(param.value, copy=True)
                    updated.flat[idx] = param.median[idx]
                    param.value = updated
                continue

            param = getattr(model, param_name)
            valid_samples = param_samples[~np.isnan(param_samples)]
            if len(valid_samples) == 0:
                continue

            param.std = np.std(valid_samples)
            param.median = np.percentile(valid_samples, 50)
            lolim, uplim = extract_limits(param, param_samples, lower_percentile, upper_percentile)
            param.lolim = lolim
            param.uplim = uplim
            param.percentiles = {p: np.percentile(valid_samples, p) for p in percentiles}

            if set_values and np.isfinite(param.median):
                param.value = param.median

            if verbose:
                print(
                    f"  {param_name}: {param.value:.6g} ± {param.std:.6g} "
                    f"(median: {param.median:.6g}) [{param.lolim:.6g}, {param.uplim:.6g}]"
                )

        if verbose:
            print(f"✓ Attached uncertainties with {confidence}% confidence intervals")

    @staticmethod
    def detach(model):
        """Remove bootstrap uncertainty attributes from model parameters."""
        for param_name in model.param_names:
            param = getattr(model, param_name)
            for attr in ['std', 'median', 'lolim', 'uplim', 'percentiles', 'samples']:
                if not hasattr(param, attr):
                    continue
                try:
                    delattr(param, attr)
                except (AttributeError, TypeError):
                    setattr(param, attr, None)


def bootstrap(model, fitter=None, x=None, y=None, yerr=None, weights=None,
              n_samples=1000, statistic='gauss', fitter_kwargs=None, seed=None,
              verbose=False, nproc=1, batch=False,
              inplace=True, confidence=68, set_values=True, noise_dist='gauss',
              xerr=None, perturb_x=False):
    """Estimate parameter uncertainties via Flux Randomization (Empirical Monte Carlo).

    Generates n_samples synthetic spectra by perturbing the observed flux
    with the measured uncertainties (flux randomization, Peterson et al. 1998,
    PASP 110, 660). The fitted model is refitted to each realization; the
    resulting parameter distributions give the uncertainties.

    Parameters
    ----------
    model : Astropy model
        Fitted model whose parameters carry the starting values.
    fitter : Fitter, optional
        Fitter for each iteration. Defaults to ``ScipyTRF()``, which uses a
        numeric Jacobian and native bounds — robust for complex/degenerate
        models. Astropy's ``TRFLSQFitter`` can converge prematurely on
        high-dimensional compound models.
    x, y, yerr : array-like
        Observed wavelengths, fluxes, and 1-sigma uncertainties.
    n_samples : int
        Number of Monte Carlo iterations.
    statistic : str
        ``'gauss'`` (default) for chi-squared fitting with Gaussian/uniform
        noise; ``'poisson'`` for raw-count data.
    noise_dist : str
        ``'gauss'`` (default) — perturb each pixel as Normal(y_obs, sigma).
        ``'uniform'`` — perturb as Uniform(y_obs ± √3·sigma), which has the
        same variance as the Gaussian case.
    inplace : bool
        If True (default), attach std/lolim/uplim to *model* parameters after
        sampling.
    confidence : float
        Confidence interval percentage (default 68 ≈ 1σ).
    set_values : bool
        If *inplace*, update parameter values to bootstrap medians.
    seed : int or None
        Random seed for reproducibility.
    """
    return Bootstrap(
        model=model,
        fitter=fitter,
        x=x,
        y=y,
        yerr=yerr,
        weights=weights,
        n_samples=n_samples,
        statistic=statistic,
        fitter_kwargs=fitter_kwargs,
        seed=seed,
        verbose=verbose,
        nproc=nproc,
        batch=batch,
        inplace=inplace,
        confidence=confidence,
        set_values=set_values,
        noise_dist=noise_dist,
        xerr=xerr,
        perturb_x=perturb_x,
    ).run()


def attach(model, samples, confidence=68, percentiles=None, verbose=False, set_values=True):
    """Compatibility wrapper around Bootstrap.attach(...)."""
    Bootstrap.attach(
        model=model,
        samples=samples,
        confidence=confidence,
        percentiles=percentiles,
        verbose=verbose,
        set_values=set_values,
    )


def detach(model):
    """Compatibility wrapper around Bootstrap.detach(...)."""
    Bootstrap.detach(model)
